# Generated by Django 3.2.25 on 2024-08-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anotherapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='course',
            new_name='category',
        ),
    ]
