# Generated by Django 3.2.25 on 2024-08-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cousine', models.CharField(max_length=100)),
                ('prince', models.IntegerField()),
            ],
        ),
    ]
