# Generated by Django 3.2.25 on 2024-08-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='cousine',
            new_name='cuosine',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='prince',
            new_name='price',
        ),
    ]
